### ISSUE TITLE
Analyze spec-v1 and make corresponding updates

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#131]
# Overview

There is a many new stuff in http://specs.frictionlessdata.io/table-schema/ (v1) that should be analyzed and implemented (and not covered by existed issues):
- json pointers
- dedicated tabular resource spec
- tableschema update - https://github.com/frictionlessdata/jsontableschema-py/issues/150
- etc

# Notes

- Because the publicly exposed schemas in the registry never use `$ref` anymore, there is no need for multiple http calls to build a schema when the registry component of a lib is used. that dereferencing is now done at build time, and so the consumer gets denormalised JSON Schemas, which is different to before. it should make the extra refresolver handling in libs ( example: https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/schema.py#L105  ) unnecessary.

# Tasks

- [x] make analysis
- [x] check validate license name (#12) (Open Definition license ID has been removed from the spec)
- [x] ensure parsing dates (#91) (fixed in https://github.com/frictionlessdata/tableschema-py/pull/159)
- [x] rebase on  spec-v1 jsonschemas and registry.json (#133)
- [x] don't dereference jsonschemas (it's already denormalized)
- [x] implement `resource.schema` and `resource.dialect` dereferencing
- [x] apply defaults (profile, resource.profile, resource.encoding, resource.dialect, resource.schema)
- [x] implement spec-v1 `resource.data` with `resource.path/url` deprecated support (#119)
- [x] DataPackage shoudn't get `schema/profile` argument anymore (now part of descriptor)
- [x] https://github.com/frictionlessdata/stack/issues/8
- [x] provide feedback to specs
