### ISSUE TITLE
Rebase push/pull_datapackage on specs-v1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#132]
# Overview

We need to rebase our `push/pull_datapackage` mechanism on specs-v1. Also there is some fixes we should make (see tasks).

# Tasks

- [x] wait decision on https://github.com/frictionlessdata/specs/issues/388
- [x] make required changes
- [x] ensure it supports url as location specifier (#81)  
- [x] ensure support for inlined data (#84)
- [x] ensure fixed resource has no name using pull_datapackage (#129)
- [x] ensure resource naming on exporting is improved (#110)
- [x] ensure that `package.save` also allow to save only package descriptor as per http://specs.frictionlessdata.io/implementation/
