### ISSUE TITLE
Update Registry class

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#133]
# Overview

It should be rebased on `registry.json` + analyze what's also should be done. For example:

# Tasks

- [x] ~rename to Registry(?) from Schema~
- [x] ~possible move to `tableschema` level (it should be re-usable)~
- [x] update this class to work with new `registry.json`
- [x] finalize class API to v1 release - MOVED to #93

**Comment by pwalsh** [comment]
@roll please outline "other improvements if needed" - I'm being super careful not to have feature creep here. If you mean "remove ref resolving code", then great, but be explicit.

**Comment by roll** [comment]
@pwalsh 
We have the whole registly/schema system in:
- https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/registry.py
- https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/schema.py

Also we have it implemented based on my latest design here:
- https://github.com/frictionlessdata/datapackage-js/blob/master/src/profiles.js
- with schemas updating system

Now with spec-v1 it seems we could share this functionality between `tableschema` and `datapackage` (it means making it public API).

In a few month this code will be replicated to 8 new languages so I just need properly finalize an API/workflow of it. It includes some analysis and final decision how it should look for v1. It's mostly about an API and not the writing code.

**Comment by pwalsh** [comment]
@roll do we really need it for tableschema? Do you think we do because the new Data Resource specs will live in that library? I'd really prefer not to add this to Table Schema.

**Comment by roll** [comment]
@pwalsh 
I doubt it. I also prefer to have it here and as private API. Just something to check.
