### ISSUE TITLE
Sync validation/update systems with stack libraries

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#142]
# Overview

Across all libraries we provide consistent validation interface:

```python
# Raise on invalid
dp = DataPackage(invalid_descriptor) # raise list of errors

# Non-strict mode
dp = DataPackage(invalid_descriptor, strict=False)
dp.valid # False
dp.errors # list of errors

# Validate function
validate(invalid_descriptor) # raise list of errors
```

The same consistency should be for update system.

# Tasks

- [ ] sync implementation with described interface
- [ ] sync public `Profile` class with described interface
- [ ] sync descriptor update system with https://github.com/frictionlessdata/tableschema-py/issues/167
