### ISSUE TITLE
Comprehensive readme for package users

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#68]
# Overview

Datapackage is one of the most important package in our eco-system. Also it's the most high-level (public facing). So eventually to have comprehensive readme like https://github.com/frictionlessdata/jsontableschema-py is vital.

# Tasks

- [ ] update readme
- [ ] add examples
- [ ] check code in readme/example works
- [ ] fix readme on PyPi (see other libs approach)
- [ ] be clearer what `validate` does (#126)
- [ ] mark `push/pull_datapackage` as a provisional API (#130)

**Comment by danfowler** [comment]
:+1:

**Comment by roll** [comment]
MERGED
#93
