### ISSUE TITLE
Release version-1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-py#93]
# Overview

Here is meta issue for tracking progress of `datapackage-v1` release. Any thoughts, ideas and comments are welcome. See corresponding milestone for the list of included issues (just started to fill it).

# Tasks

- [x] sync `Profile` classes with Stack Reference
- [x] rename `specs` folder to `profiles` folder
- [x] remove deprecated code [-v1)
- [x] release ALPHA
---
- [x] remove `alpha` from dependencies
- [x] csv dialect - review `caseSensitiveHeader`, `nullSequence`, `header` (https://github.com/frictionlessdata/specs/issues/405)
- [x] review/improve descriptor updating logic (!!!)
- [x] add `Resource.config(**table_options)`
- [x] expose package version (init, CLI)
- [x] sync validation semantic - `Datapackage(strict=True)`
- [x] expose `validate` function
- [x] add examples
- [x] check code in readme/example works
- [x] fix readme on PyPi (see other libs approach)
- [x] be clearer what `validate` does (#126)
- [x] mark `push/pull_datapackage` as a provisional and deprecated API (#130)
- [x] cache `Resource.table` (!!!)
- [x] replace `dafault_base_path` by `base_path`
- [x] it seems validation still have to be composable (on datapackage and resource levels) - consider plain data package with some tabular resources) - IMPORTANT!
- [x] fix pytest warning `datapackage/registry.py:40: ResourceWarning: unclosed file`
- [ ] release

**Comment by rgieseke** [comment]
As suggested by @danfowler copying from Gitter chat:

> After discussions here frictionlessdata/jsontableschema-pandas-py#8 and the tutorial by @danfowler above I wrote a function to load a data package into a Pandas DataFrame directly: https://github.com/openclimatedata/notebooks/blob/master/pandas_datapackage_reader.py

> It's modeled after pandas read_excel (or read_csv), just not having to do any of the skiprows, index_col-dance that is already done in the data package 

> For me that works great and I'd happy to get any feedback you might have!
You can see it in action here, also pulling in the population data package: https://github.com/openclimatedata/notebooks/blob/master/Global%20Carbon%20Budget%20%7C%20Fossil%20Fuel%20and%20Cement%20Production.ipynb

> I could turn this into a small separate module but it could also be included in one of the existing ones if it makes sense.

I think this could also be a `to_pandas` or `to_dataframe` method, but `read_datapackage`  is closer to what a Pandas user would be used to.
